#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriUMModel;


namespace AriUMModel	
{
	public partial class AriUMContext : OpenAccessContext, IAriUMContextUnitOfWork
	{
		private static string connectionStringName = @"AriUMDBConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AriUMEntities.rlinq");
	
		public AriUMContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AriUMContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public AriUMContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AriUMContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriUMContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<User> Users 
		{
	    	get
	    	{
	        	return this.GetAll<User>();
	    	}
		}
		
		public IQueryable<UserGroup> UserGroups 
		{
	    	get
	    	{
	        	return this.GetAll<UserGroup>();
	    	}
		}
		
		public IQueryable<Customer> Customers 
		{
	    	get
	    	{
	        	return this.GetAll<Customer>();
	    	}
		}
		
		public IQueryable<Product> Products 
		{
	    	get
	    	{
	        	return this.GetAll<Product>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}

	public interface IAriUMContextUnitOfWork : IUnitOfWork
	{
		IQueryable<User> Users 
		{ 
			get;
		}

		IQueryable<UserGroup> UserGroups 
		{ 
			get;
		}

		IQueryable<Customer> Customers 
		{ 
			get;
		}

		IQueryable<Product> Products 
		{ 
			get;
		}

	}
}

namespace AriUMModel	
{
	public partial class User
	{
		private int _userId;
		public virtual int UserId 
		{ 
		    get
		    {
		        return this._userId;
		    }
		    set
		    {
		        this._userId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _email;
		public virtual string Email 
		{ 
		    get
		    {
		        return this._email;
		    }
		    set
		    {
		        this._email = value;
		    }
		}
		
		private string _password;
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private int? _user_group_id;
		public virtual int? User_group_id 
		{ 
		    get
		    {
		        return this._user_group_id;
		    }
		    set
		    {
		        this._user_group_id = value;
		    }
		}
		
		private UserGroup _userGroup;
		public virtual UserGroup UserGroup 
		{ 
		    get
		    {
		        return this._userGroup;
		    }
		    set
		    {
		        this._userGroup = value;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class UserGroup
	{
		private int _userGroupId;
		public virtual int UserGroupId 
		{ 
		    get
		    {
		        return this._userGroupId;
		    }
		    set
		    {
		        this._userGroupId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class Customer
	{
		private int _customerId;
		public virtual int CustomerId 
		{ 
		    get
		    {
		        return this._customerId;
		    }
		    set
		    {
		        this._customerId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _serialInvoice;
		public virtual string SerialInvoice 
		{ 
		    get
		    {
		        return this._serialInvoice;
		    }
		    set
		    {
		        this._serialInvoice = value;
		    }
		}
		
		private string _address;
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
		        this._address = value;
		    }
		}
		
		private string _nif;
		public virtual string Nif 
		{ 
		    get
		    {
		        return this._nif;
		    }
		    set
		    {
		        this._nif = value;
		    }
		}
		
		private string _city;
		public virtual string City 
		{ 
		    get
		    {
		        return this._city;
		    }
		    set
		    {
		        this._city = value;
		    }
		}
		
		private string _state;
		public virtual string State 
		{ 
		    get
		    {
		        return this._state;
		    }
		    set
		    {
		        this._state = value;
		    }
		}
		
		private string _country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this._country;
		    }
		    set
		    {
		        this._country = value;
		    }
		}
		
		private string _codPostal;
		public virtual string CodPostal 
		{ 
		    get
		    {
		        return this._codPostal;
		    }
		    set
		    {
		        this._codPostal = value;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class Product
	{
		private int _productId;
		public virtual int ProductId 
		{ 
		    get
		    {
		        return this._productId;
		    }
		    set
		    {
		        this._productId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private decimal _price;
		public virtual decimal Price 
		{ 
		    get
		    {
		        return this._price;
		    }
		    set
		    {
		        this._price = value;
		    }
		}
		
	}
}
#pragma warning restore 1591

