#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriUMModel;


namespace AriUMModel	
{
	public partial class AriUMContext : OpenAccessContext, IAriUMContextUnitOfWork
	{
		private static string connectionStringName = @"AriUMDBConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AriUMEntities.rlinq");
	
		public AriUMContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AriUMContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public AriUMContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AriUMContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriUMContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<User> Users 
		{
	    	get
	    	{
	        	return this.GetAll<User>();
	    	}
		}
		
		public IQueryable<UserGroup> UserGroups 
		{
	    	get
	    	{
	        	return this.GetAll<UserGroup>();
	    	}
		}
		
		public IQueryable<Customer> Customers 
		{
	    	get
	    	{
	        	return this.GetAll<Customer>();
	    	}
		}
		
		public IQueryable<Product> Products 
		{
	    	get
	    	{
	        	return this.GetAll<Product>();
	    	}
		}
		
		public IQueryable<Invoice> Invoices 
		{
	    	get
	    	{
	        	return this.GetAll<Invoice>();
	    	}
		}
		
		public IQueryable<InvoiceLine> InvoiceLines 
		{
	    	get
	    	{
	        	return this.GetAll<InvoiceLine>();
	    	}
		}
		
		public IQueryable<WebApiTicket> WebApiTickets 
		{
	    	get
	    	{
	        	return this.GetAll<WebApiTicket>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}

	public interface IAriUMContextUnitOfWork : IUnitOfWork
	{
		IQueryable<User> Users 
		{ 
			get;
		}

		IQueryable<UserGroup> UserGroups 
		{ 
			get;
		}

		IQueryable<Customer> Customers 
		{ 
			get;
		}

		IQueryable<Product> Products 
		{ 
			get;
		}

		IQueryable<Invoice> Invoices 
		{ 
			get;
		}

		IQueryable<InvoiceLine> InvoiceLines 
		{ 
			get;
		}

		IQueryable<WebApiTicket> WebApiTickets 
		{ 
			get;
		}

	}
}

namespace AriUMModel	
{
	public partial class User
	{
		private int _userId;
		public virtual int UserId 
		{ 
		    get
		    {
		        return this._userId;
		    }
		    set
		    {
		        this._userId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _email;
		public virtual string Email 
		{ 
		    get
		    {
		        return this._email;
		    }
		    set
		    {
		        this._email = value;
		    }
		}
		
		private string _password;
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private string _login;
		public virtual string Login 
		{ 
		    get
		    {
		        return this._login;
		    }
		    set
		    {
		        this._login = value;
		    }
		}
		
		private UserGroup _userGroup;
		public virtual UserGroup UserGroup 
		{ 
		    get
		    {
		        return this._userGroup;
		    }
		    set
		    {
		        this._userGroup = value;
		    }
		}
		
		private IList<WebApiTicket> _webApiTickets = new List<WebApiTicket>();
		public virtual IList<WebApiTicket> WebApiTickets 
		{ 
		    get
		    {
		        return this._webApiTickets;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class UserGroup
	{
		private int _userGroupId;
		public virtual int UserGroupId 
		{ 
		    get
		    {
		        return this._userGroupId;
		    }
		    set
		    {
		        this._userGroupId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class Customer
	{
		private int _customerId;
		public virtual int CustomerId 
		{ 
		    get
		    {
		        return this._customerId;
		    }
		    set
		    {
		        this._customerId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _serialInvoice;
		public virtual string SerialInvoice 
		{ 
		    get
		    {
		        return this._serialInvoice;
		    }
		    set
		    {
		        this._serialInvoice = value;
		    }
		}
		
		private string _address;
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
		        this._address = value;
		    }
		}
		
		private string _nif;
		public virtual string Nif 
		{ 
		    get
		    {
		        return this._nif;
		    }
		    set
		    {
		        this._nif = value;
		    }
		}
		
		private string _city;
		public virtual string City 
		{ 
		    get
		    {
		        return this._city;
		    }
		    set
		    {
		        this._city = value;
		    }
		}
		
		private string _state;
		public virtual string State 
		{ 
		    get
		    {
		        return this._state;
		    }
		    set
		    {
		        this._state = value;
		    }
		}
		
		private string _country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this._country;
		    }
		    set
		    {
		        this._country = value;
		    }
		}
		
		private string _codPostal;
		public virtual string CodPostal 
		{ 
		    get
		    {
		        return this._codPostal;
		    }
		    set
		    {
		        this._codPostal = value;
		    }
		}
		
		private IList<Invoice> _invoices = new List<Invoice>();
		public virtual IList<Invoice> Invoices 
		{ 
		    get
		    {
		        return this._invoices;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class Product
	{
		private int _productId;
		public virtual int ProductId 
		{ 
		    get
		    {
		        return this._productId;
		    }
		    set
		    {
		        this._productId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private decimal _price;
		public virtual decimal Price 
		{ 
		    get
		    {
		        return this._price;
		    }
		    set
		    {
		        this._price = value;
		    }
		}
		
		private IList<InvoiceLine> _invoiceLines = new List<InvoiceLine>();
		public virtual IList<InvoiceLine> InvoiceLines 
		{ 
		    get
		    {
		        return this._invoiceLines;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class Invoice
	{
		private int _invoiceId;
		public virtual int InvoiceId 
		{ 
		    get
		    {
		        return this._invoiceId;
		    }
		    set
		    {
		        this._invoiceId = value;
		    }
		}
		
		private DateTime _invoiceDate;
		public virtual DateTime InvoiceDate 
		{ 
		    get
		    {
		        return this._invoiceDate;
		    }
		    set
		    {
		        this._invoiceDate = value;
		    }
		}
		
		private string _serial;
		public virtual string Serial 
		{ 
		    get
		    {
		        return this._serial;
		    }
		    set
		    {
		        this._serial = value;
		    }
		}
		
		private int _invoiceNumber;
		public virtual int InvoiceNumber 
		{ 
		    get
		    {
		        return this._invoiceNumber;
		    }
		    set
		    {
		        this._invoiceNumber = value;
		    }
		}
		
		private decimal _total;
		public virtual decimal Total 
		{ 
		    get
		    {
		        return this._total;
		    }
		    set
		    {
		        this._total = value;
		    }
		}
		
		private int _year;
		public virtual int Year 
		{ 
		    get
		    {
		        return this._year;
		    }
		    set
		    {
		        this._year = value;
		    }
		}
		
		private Customer _customer;
		public virtual Customer Customer 
		{ 
		    get
		    {
		        return this._customer;
		    }
		    set
		    {
		        this._customer = value;
		    }
		}
		
		private IList<InvoiceLine> _invoiceLines = new List<InvoiceLine>();
		public virtual IList<InvoiceLine> InvoiceLines 
		{ 
		    get
		    {
		        return this._invoiceLines;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class InvoiceLine
	{
		private int _invoiceLineId;
		public virtual int InvoiceLineId 
		{ 
		    get
		    {
		        return this._invoiceLineId;
		    }
		    set
		    {
		        this._invoiceLineId = value;
		    }
		}
		
		private int _quantity;
		public virtual int Quantity 
		{ 
		    get
		    {
		        return this._quantity;
		    }
		    set
		    {
		        this._quantity = value;
		    }
		}
		
		private decimal _amount;
		public virtual decimal Amount 
		{ 
		    get
		    {
		        return this._amount;
		    }
		    set
		    {
		        this._amount = value;
		    }
		}
		
		private decimal _price;
		public virtual decimal Price 
		{ 
		    get
		    {
		        return this._price;
		    }
		    set
		    {
		        this._price = value;
		    }
		}
		
		private Invoice _invoice;
		public virtual Invoice Invoice 
		{ 
		    get
		    {
		        return this._invoice;
		    }
		    set
		    {
		        this._invoice = value;
		    }
		}
		
		private Product _product;
		public virtual Product Product 
		{ 
		    get
		    {
		        return this._product;
		    }
		    set
		    {
		        this._product = value;
		    }
		}
		
	}
}

namespace AriUMModel	
{
	public partial class WebApiTicket
	{
		private int _webApiTicketId;
		public virtual int WebApiTicketId 
		{ 
		    get
		    {
		        return this._webApiTicketId;
		    }
		    set
		    {
		        this._webApiTicketId = value;
		    }
		}
		
		private DateTime _start;
		public virtual DateTime Start 
		{ 
		    get
		    {
		        return this._start;
		    }
		    set
		    {
		        this._start = value;
		    }
		}
		
		private DateTime _end;
		public virtual DateTime End 
		{ 
		    get
		    {
		        return this._end;
		    }
		    set
		    {
		        this._end = value;
		    }
		}
		
		private string _code;
		public virtual string Code 
		{ 
		    get
		    {
		        return this._code;
		    }
		    set
		    {
		        this._code = value;
		    }
		}
		
		private User _user;
		public virtual User User 
		{ 
		    get
		    {
		        return this._user;
		    }
		    set
		    {
		        this._user = value;
		    }
		}
		
	}
}
#pragma warning restore 1591

